libhugetlbfs: tests: adding missing header file falloc.h
Building libhugetlbfs failed on CentOS due below error.
Adding missing header file linux/falloc.h will fix this build error.

Error log:
	 CC64 obj64/fallocate_basic.o
fallocate_basic.c: In function ‘main’:
fallocate_basic.c:78:22: error: ‘FALLOC_FL_PUNCH_HOLE’ undeclared (first use in this function)
  err = fallocate(fd, FALLOC_FL_PUNCH_HOLE | FALLOC_FL_KEEP_SIZE,
                      ^
fallocate_basic.c:78:22: note: each undeclared identifier is reported only once for each function it appears in
fallocate_basic.c:78:45: error: ‘FALLOC_FL_KEEP_SIZE’ undeclared (first use in this function)
  err = fallocate(fd, FALLOC_FL_PUNCH_HOLE | FALLOC_FL_KEEP_SIZE,
                                             ^
make[1]: *** [obj64/fallocate_basic.o] Error 1
make: *** [tests/all] Error 2

Signed-off-by: Naresh Kamboju <naresh.kamboju@linaro.org>
Signed-off-by: Eric B Munson <emunson@mgebm.net>