Do not use 'restrict' word for variable name
'restrict' is reserved starting from C99. This causes compilation
error with GCC 5.1 that uses -std=c99 by default.

 CC64 obj64/hugeutils.o
 hugeutils.c: In function ‘__lh_hugetlbfs_setup_env’:
 hugeutils.c:304:40: error: expected identifier or ‘(’ before ‘restrict’
 char *p, *tok, *exe, buf[MAX_EXE+1], restrict[MAX_EXE];
 ^
 hugeutils.c:309:11: error: expected expression before ‘restrict’

Signed-off-by: Anatol Pomozov <anatol.pomozov@gmail.com>